import React, { useState, useCallback } from 'react';
import CodeMirror from '@uiw/react-codemirror';
import { sql } from '@codemirror/lang-sql';
import { oneDark } from '@codemirror/theme-one-dark';
import { EditorView } from '@codemirror/view';
import { queryApi } from '../services/api';
import './QueryEditor.css';

export default function QueryEditor({
  activeConnection, currentQuery, onQueryChange, onSetSqlQuery,
  onExecuting, onQueryExecuted,
  queryType, onQueryTypeChange, theme,
}) {
  const [maxResults, setMaxResults] = useState(500);
  const [sqlModal, setSqlModal]     = useState(null);   // generated SQL string
  const [sqlLoading, setSqlLoading] = useState(false);
  const [sqlError, setSqlError]     = useState('');
  const [copied, setCopied]         = useState(false);

  const execute = useCallback(async () => {
    if (!activeConnection) return;
    const q = currentQuery.trim();
    if (!q) return;
    onExecuting();
    try {
      const res = await queryApi.execute({ connectionId: activeConnection.id, query: q, queryType, maxResults });
      const payload = res.data;
      if (payload.success) {
        onQueryExecuted({ ...payload.data, success: true }, q);
      } else {
        onQueryExecuted({ success: false, message: payload.message }, q);
      }
    } catch (e) {
      onQueryExecuted({ success: false, message: e.response?.data?.message || e.message }, currentQuery);
    }
  }, [activeConnection, currentQuery, queryType, maxResults, onExecuting, onQueryExecuted]);

  const showSql = useCallback(async () => {
    if (!activeConnection || !currentQuery.trim()) return;
    setSqlLoading(true); setSqlError(''); setSqlModal(null);
    try {
      const res = await queryApi.explain({ connectionId: activeConnection.id, query: currentQuery.trim() });
      if (res.data.success) {
        setSqlModal(res.data.data);
      } else {
        setSqlError(res.data.message);
        setSqlModal('');
      }
    } catch (e) {
      setSqlError(e.response?.data?.message || e.message);
      setSqlModal('');
    } finally { setSqlLoading(false); }
  }, [activeConnection, currentQuery]);

  const handleKeyDown = useCallback((e) => {
    if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') { e.preventDefault(); execute(); }
  }, [execute]);

  return (
    <div className="query-editor" onKeyDown={handleKeyDown}>
      <div className="editor-toolbar">
        <div className="query-type-tabs">
          {['SQL', 'HQL'].map(t => (
            <button key={t} className={`type-tab ${queryType === t ? 'active' : ''}`}
              onClick={() => onQueryTypeChange(t)}>{t}</button>
          ))}
        </div>

        <div className="editor-actions">
          {queryType === 'HQL' && (
            <button className="show-sql-btn" onClick={showSql}
              disabled={sqlLoading || !activeConnection || !currentQuery.trim()}
              title="Show equivalent SQL generated by Hibernate">
              {sqlLoading ? 'Translating…' : '</> Show SQL'}
            </button>
          )}
          <label className="limit-label">
            Limit
            <input type="number" className="limit-input" value={maxResults} min={1} max={5000}
              onChange={e => setMaxResults(parseInt(e.target.value, 10) || 500)} />
          </label>
          <button className="run-btn" onClick={execute} disabled={!activeConnection} title="Run (Ctrl+Enter)">
            ▶ Run
          </button>
        </div>
      </div>

      <div className="editor-area">
        <CodeMirror
          value={currentQuery}
          height="100%"
          theme={theme === 'light' ? 'light' : oneDark}
          extensions={[sql(), EditorView.lineWrapping]}
          onChange={onQueryChange}
          basicSetup={{ lineNumbers: true, foldGutter: false, highlightActiveLine: true }}
        />
      </div>

      {!activeConnection && (
        <div className="editor-overlay">
          <span>Connect to a database to start querying</span>
        </div>
      )}

      {/* Show SQL modal */}
      {sqlModal !== null && (
        <div className="modal-overlay" onClick={() => setSqlModal(null)}>
          <div className="modal sql-modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <span>Generated SQL</span>
              <button className="modal-close" onClick={() => setSqlModal(null)}>✕</button>
            </div>
            <div className="modal-body">
              {sqlError
                ? <div className="path-error">{sqlError}</div>
                : <pre className="generated-sql">{sqlModal}</pre>}
            </div>
            <div className="modal-footer">
              <button className="btn btn-ghost" onClick={() => setSqlModal(null)}>Close</button>
              {!sqlError && (<>
                <button className="btn btn-ghost copy-sql-btn" onClick={() => {
                  navigator.clipboard.writeText(sqlModal).then(() => {
                    setCopied(true);
                    setTimeout(() => setCopied(false), 1800);
                  });
                }}>
                  {copied ? '✓ Copied' : 'Copy SQL'}
                </button>
                <button className="btn btn-primary" onClick={() => { (onSetSqlQuery || onQueryChange)(sqlModal); onQueryTypeChange('SQL'); setSqlModal(null); }}>
                  Use as SQL
                </button>
              </>)}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
